### PR TITLE
BigGraph Generation Option for Diffusion Data and Utils Refactor

### PR DESCRIPTION
**Pull request by ebridge2**
# New Features
+ added big-graph generation code building on Disa's mrcap workflow
+ added ability to post-analysis produce big-graphs with `biggraph_pipeline` that takes streamlines and produces graphs

# Reorganization
+ replaced `utils` class with `utils` module that uses functions instead of a class with class functions; this makes accessing utilities not require an instance of the utils class
+ added wrapper for `ndmg_dwi_pipeline` so that we can catch rudimentarily catch exceptions, since otherwise the entire chain of jobs would fail if one exception is reached

# Validation

## Big-Graph Testing

+ confirmation that the big-graphs produced are valid [big-graph notebook](https://github.com/NeuroDataDesign/fngs/blob/master/docs/ebridge2/mrilab/week_0714/biggraph_exps.ipynb)
+ demonstration that the pipeline is functional with the utils reorganization and for generating big-graphs
```
# somewhere that has FSL set up already
git clone -b eric-dev-bg-2 https://github.com/neurodata/ndmg.git
python setup.py install
ndmg_demo-dwi
```

## Utils
+ demonstration that before, we needed a utils instance to call a function, whereas now, we only need the function itself

### Before
```
import ndmg.utils as ndu
# makes a ndu instance and then calls the function, which is unnecessary time
# and memory spent allocating an instance
ndu().extract_brain(img) 
```
### After
```
import ndmg.utils as ndu
# now we can just call the function we want directly
ndu.extract_brain(img)
```

### CODE REVIEW

**Comment by gkiar** [comment]
@ebridge2 why are all the tests failing?

**Comment by gkiar** [comment]
The point of all of these is that we should be making graphs and providing code that we understand. This PR has MANY commits, changed a lot of code in small ways, some in bigger ways, but ultimately beyond reading code I don't see tests or evidence that these changes produced the desired result in that it makes the tool *better*, or do something it didn't before (that we can trust).

This concept is what I had been talking about in the previous PR - everything you want to merge, you need to explain concisely and provide evidence for. Avoid bloat (commits unrelated to the PR's purpose), and provide evidence of success.

**Comment by ebridge2** [comment]
"Can you please provide some evidence that the connectomes generated before your changes (using parcellations) are the same as after?" you mean the graphs produced by graphs/graphs.py, ie, verifying that the utils refactor did not change anything?

"Also, can you provide proof that this is working/doing something favourable?" analyze these properties using flashX?

**Comment by gkiar** [comment]
- I do mean that you should verify (via checksum or otherwise) that no changes were made to the main implementation. This should be trivial and can be done with the demo taking < 7 minutes (to run both before and after)
- I don't care what library you use, but these properties should be explored at least to some extent, i.e. we shouldn't give out graphs when we don't know how many nodes they have or if they all have the same amount, and that the amount is meaningful

**Pull request closed without merging**
