### PR TITLE
Eric dev merge

### PR DESCRIPTION
**Pull request by ebridge2**
see previous pull request for comments addressed in this one.

### CODE REVIEW

**Comment by ebridge2** [comment]
If you check out the "checks" section, there seems to be some sort of problem with the dockerfile; I edited the docker file to add the ndmg-bids fngs leg and I think that might have somehow messed it up, as it returned a weird error about submodules and the changes that I made are not actually reflected in the repo.

**Comment by gkiar** [comment]
You shouldn't change the docker file **at all**. As we discussed, you should make the fmri pipeline an option for the ndmg_bids script (i.e. command line flag and a module that handles it).

Also, why is this PR so long, including things I did on master? I suspect is has something to do with git history when I had to purge the large files from the repo. Can you please do the following:

- clone a fresh version of the repo
- create a new branch from master entitled `eric-dev-merge-2`
- copy the changes you made here over to that new branch
- push to that new branch and make a PR from it.

**Comment by ebridge2** [comment]
yah; the PR messed up some dependencies, and I had to do a big merge to get them correctly adjusted. I'll get that fixed and then we should be good? Do you have any other feedback in the meantime?

**Comment by gkiar** [comment]
There were too many things, I couldn't tell what I was supposed to review. Please follow the above instructions as closely as possible (important that you clone a fresh version of the repo and start a new branch), then open a new one and I'll check back.

**Pull request closed without merging**
