### PR TITLE
Add python3, conda support

### PR DESCRIPTION
**Pull request by davclark**
This was easy to do automatically with 2to3. I excluded the dict conversions, as you were using items() where an iterator would have been appropriate already.

conda support is just adding the conda-requirements.txt file. It's equivalent to the pip version, but works with `conda --file conda-requirements.txt`.

I also added comments in a variety of places where automated linting was able to detect compilation errors.

I have not been able to verify that this codebase still works, as the recommended pipeline surface test from the README crashes when it tries to access `tests/data/outputs/tmp/KKI2009_113_1_DTI_s4_t1_t2.nii.gz` before it's created. This is because FSL's eddy_correct crashes if it finds a python 3 interpreter named `python`, which is what happens when you're using conda.

But this is trivial enough that I'm pretty sure it's right. At least it's a starting point.

### CODE REVIEW

**Comment by davclark** [comment]
It turns out there is a recently released patch to take FSL to 5.0.10-python3:

http://fsl.fmrib.ox.ac.uk/fsldownloads/patches/fsl-5.0.10-python3.tar.gz

Alternatively, you can manually modify the current scripts like so:

    #!/usr/bin/env python**2**

Sample pipeline from the README now seems to work.

**Comment by gkiar** [comment]
Thanks, @davclark . I just tested the changes locally and it is working as expected. I'd been meaning to run 2to3, so thanks for that! I also appreciate the code audit/added comments. Cheers :)

**Comment by davclark** [comment]
Happy new year! FYI I called the branch "arbitrary" because none of our data is in BIDS format - so I'll proceed to work on the ability to ingest non-BIDS (i.e., arbitrarily) formatted directories of brain data.

**Comment by gkiar** [comment]
Great, I look forward to seeing the addition!

**Pull request merged**
