### PR TITLE
Travis updates

### PR DESCRIPTION
**Pull request by loftusa**
travis is now working, as a matrix!! (tests MNI, native, and native_dsn on push).

Also refactored the way it gets input data, and the way it pip installs ndmg, to a way that's much cleaner, and also fixes the forking issue.

unfortunately, travis currently times out every time because of ndmg's new longer runtime, but the logs are quite useful. 

See:
https://travis-ci.org/neurodata/ndmg/jobs/568597545
https://travis-ci.org/neurodata/ndmg/jobs/568597544

### CODE REVIEW

**Comment by dPys** [comment]
Great news @loftusa !!! good job!!

@dPys

**Comment by dPys** [comment]
Only thing is-- 

I see: The command "docker exec -w /ndmg travis ndmg_bids --sp $SP --participant_label 0025864 --session_label 1 --modality dwi --atlas desikan /input /output participant" exited with 1.

Is there a reason why it's still calling a docker command? it shouldn't be right?

**Comment by loftusa** [comment]
> Only thing is--
> 
> I see: The command "docker exec -w /ndmg travis ndmg_bids --sp $SP --participant_label 0025864 --session_label 1 --modality dwi --atlas desikan /input /output participant" exited with 1.
> 
> Is there a reason why it's still calling a docker command? it shouldn't be right?

It's still calling docker commands. I decided not to use pytest for now - travis's build matrix makes it really easy to parallelize outside of it, and I don't see a good enough reason to run ndmg_dwi_pipeline inside pytest yet

We'll need to use docker regardless, since otherwise we don't have FSL / AFNI

Check out the new travis.yml file - the matrix stuff you can do is pretty dope

**Comment by dPys** [comment]
Not true @loftusa . 
You can add the following lines to the travis.yaml for AFNI and FSL support without docker. I would use pytest and not docker if possible with travis:
```
before_install:
- if $INSTALL_DEB_DEPENDECIES; then sudo rm -rf /dev/shm; sudo ln -s /run/shm /dev/shm; fi
- travis_retry bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh);
- if $INSTALL_DEB_DEPENDECIES; then
    travis_retry sudo apt-get -y update &&
    travis_retry sudo apt-get install -y -qq fsl afni elastix fsl-atlases;
  fi;
- if $INSTALL_DEB_DEPENDECIES; then
    source /etc/fsl/fsl.sh;
    source /etc/afni/afni.sh;
    export FSLOUTPUTTYPE=NIFTI_GZ;
  fi;
```

**Comment by loftusa** [comment]
> Not true @loftusa .
> You can add the following lines to the travis.yaml for AFNI and FSL support without docker. I would use pytest and not docker if possible with travis:
> 
> ```
> before_install:
> - if $INSTALL_DEB_DEPENDECIES; then sudo rm -rf /dev/shm; sudo ln -s /run/shm /dev/shm; fi
> - travis_retry bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh);
> - if $INSTALL_DEB_DEPENDECIES; then
>     travis_retry sudo apt-get -y update &&
>     travis_retry sudo apt-get install -y -qq fsl afni elastix fsl-atlases;
>   fi;
> - if $INSTALL_DEB_DEPENDECIES; then
>     source /etc/fsl/fsl.sh;
>     source /etc/afni/afni.sh;
>     export FSLOUTPUTTYPE=NIFTI_GZ;
>   fi;
> ```

Ok, I can add this as a thing to do later?

For now I think we should merge, given that this is an improvement (e.g., without timeout, travis would be running to completion), and then iterate.

And I am absolutely certain that we are always running the correct branch now, regardless of PR, forked PR, etc (can explain why if you want!)

**Pull request merged**
