### PR TITLE
Eric dev merge2

### PR DESCRIPTION
**Pull request by ebridge2**

### CODE REVIEW

**Comment by gkiar** [comment]
Smalll notes on PR:
- `MANIFEST.in`
  - what is the point of this file?
- `ndmg/nuis/`
  - you made this folder with files in it, but didn't add it to the `ndmg/__init__.py`. Is that an oversight?
- `ndmg/register/register.py`
  - why is the function `resample_ant` called that? You say in the comments it uses dipy.
- `ndmg/scripts/fngs_pipeline.py`
  - let's rename this. I think our two pipelines should be called `ndmg_dwi` and `ndmg_fmri`. That is also consistent with the demos, ndmg_demo-dwi, etc.
- `ndmg/utils/utils.py`
  - `get_brain_data.py` should also accept nifti2 images. and I still think it should actually be called `load_nifti` because that's what it is. To be honest I'm not sure why it exists at all? The pipeline accepts the string (so loads the image from that), and your pipeline should be able to know where you have the string and where you have the image, why don't you just skip this function and keep track of the image once you load it?

I haven't yet installed and tested the pipeline yet, but that'll give you some stuff to work on in the meantime.

**Comment by ebridge2** [comment]
1. The manifest is to add a template file for the quality control. 

2. yep, thats a oversight, sorry about that :)

3. Resample antisotropic (ant) I named it this because it is the only one that resamples antisotropic images effectively. 

4. Sounds good

5. This gets niftis, nifti2, as well as numpy arrays. I added this because there are functions where I would only have a matrix in some spots (ie, a matrix of mni space coordinates and intensities at those spots), but wanted one function since I would do some code operation in another location but on niftis. This way, I can have 1 load function that does both and lets me use the same code minimally.

Ill make those changes and update accordingly.

**Comment by gkiar** [comment]
-3. I think you mean the word anisotropic, not antisotropic...
-5. I still don't understand why this is a thing? why can't you just load the image once when the pipeline starts and then depending whether the function you're calling takes an array or the full nifti pass the right one. I don't think we need a wrapper that *only* contains a one-line function call.

Also, just ran the demo. It took quite long! There was no timing info, but I was definitely waiting more than 5 min. Can you please downsample your data more in time to make this take less time?

For 1 we're fine, for 3 rename it, for 5 I have failed to be convinced we need it so I think remove.

Also, this branch doesn't have any of my demos in it, can you please merge in master?

Also, I didn't mention this, but I still don't like how the QC is 400 lines of mostly the same stuff. We can reduce that by probably 200 or more by being clever and writing that more like how I've written the [plotly plotting](https://github.com/neurodata/ndmg/blob/master/ndmg/stats/plotly_multiplot.py#L10) code, in other words, despite doing nearly identical but slightly different things and just repeating myself, I've batched things in a way that minimizes the number of lines of code. I don't know if this is good practice generally, but I like it because when I change function calls I only have to change one line rather than 10.

**Comment by gkiar** [comment]
Also, qc.py should have a better name. It doesn't do all qc, just registration I think? Then let's name it that.

**Pull request closed without merging**
